// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file bibliophage/v1alpha1/document.proto (package bibliophage, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * enums for strict classification of data,
 * rather than freeform JSON/strings
 *
 * @generated from enum bibliophage.DocumentType
 */
export enum DocumentType {
  /**
   * Default/unknown
   *
   * @generated from enum value: DOCUMENT_TYPE_UNSPECIFIED = 0;
   */
  DOCUMENT_TYPE_UNSPECIFIED = 0,

  /**
   * Least specific, unspecified documents will be turned into this
   *
   * @generated from enum value: NOTE = 1;
   */
  NOTE = 1,

  /**
   * Has some authoritative information
   *
   * @generated from enum value: LORE_FRAGMENT = 2;
   */
  LORE_FRAGMENT = 2,

  /**
   * PCs, NPCs, historical figures, ...
   *
   * @generated from enum value: CHARACTER = 3;
   */
  CHARACTER = 3,

  /**
   * Places
   *
   * @generated from enum value: LOCATION = 4;
   */
  LOCATION = 4,

  /**
   * Posessions, Items, Objects, ...
   *
   * @generated from enum value: OBJECT = 5;
   */
  OBJECT = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(DocumentType)
proto3.util.setEnumType(DocumentType, "bibliophage.DocumentType", [
  { no: 0, name: "DOCUMENT_TYPE_UNSPECIFIED" },
  { no: 1, name: "NOTE" },
  { no: 2, name: "LORE_FRAGMENT" },
  { no: 3, name: "CHARACTER" },
  { no: 4, name: "LOCATION" },
  { no: 5, name: "OBJECT" },
]);

/**
 * @generated from message bibliophage.DocumentStoreRequest
 */
export class DocumentStoreRequest extends Message<DocumentStoreRequest> {
  /**
   * Human-readable name (e.g., "Monster Manual")
   *
   * @generated from field: string document_name = 1;
   */
  documentName = "";

  /**
   * raw text content of the document
   *
   * @generated from field: string content = 2;
   */
  content = "";

  /**
   * Type of document
   *
   * @generated from field: bibliophage.DocumentType document_type = 4;
   */
  documentType = DocumentType.DOCUMENT_TYPE_UNSPECIFIED;

  constructor(data?: PartialMessage<DocumentStoreRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.DocumentStoreRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "document_type", kind: "enum", T: proto3.getEnumType(DocumentType) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DocumentStoreRequest {
    return new DocumentStoreRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DocumentStoreRequest {
    return new DocumentStoreRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DocumentStoreRequest {
    return new DocumentStoreRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DocumentStoreRequest | PlainMessage<DocumentStoreRequest> | undefined, b: DocumentStoreRequest | PlainMessage<DocumentStoreRequest> | undefined): boolean {
    return proto3.util.equals(DocumentStoreRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.DocumentStoreResponse
 */
export class DocumentStoreResponse extends Message<DocumentStoreResponse> {
  /**
   * Did it work?
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<DocumentStoreResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.DocumentStoreResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DocumentStoreResponse {
    return new DocumentStoreResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DocumentStoreResponse {
    return new DocumentStoreResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DocumentStoreResponse {
    return new DocumentStoreResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DocumentStoreResponse | PlainMessage<DocumentStoreResponse> | undefined, b: DocumentStoreResponse | PlainMessage<DocumentStoreResponse> | undefined): boolean {
    return proto3.util.equals(DocumentStoreResponse, a, b);
  }
}

