// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file bibliophage/v1alpha1/document.proto (package bibliophage, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DocumentStoreRequest, DocumentStoreResponse } from "./document_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definitions - the API endpoints
 * RPC method: takes Request, returns Response
 *
 * @generated from service bibliophage.DocumentService
 */
export const DocumentService = {
  typeName: "bibliophage.DocumentService",
  methods: {
    /**
     * @generated from rpc bibliophage.DocumentService.StoreDocument
     */
    storeDocument: {
      name: "StoreDocument",
      I: DocumentStoreRequest,
      O: DocumentStoreResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

