// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file bibliophage/v1alpha1/pdf.proto (package bibliophage, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PdfLoadRequest, PdfLoadResponse } from "./pdf_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definitions - the API endpoints
 * RPC method: takes Request, returns Response
 *
 * @generated from service bibliophage.LoadingService
 */
export const LoadingService = {
  typeName: "bibliophage.LoadingService",
  methods: {
    /**
     * @generated from rpc bibliophage.LoadingService.LoadPDF
     */
    loadPDF: {
      name: "LoadPDF",
      I: PdfLoadRequest,
      O: PdfLoadResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

