# yarn's Plug and Play does not work well with code that wants to import other code at build time
# https://yarnpkg.com/configuration/yarnrc#nodeLinker
# pnpm seems to be a middle ground between pnp and old fashioned node_imports
# and it seems to not break our code like pnp, so let's go with that
nodeLinker: pnpm
