# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: grpc_generated/api.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import grpc_generated.api_pb2 as grpc__generated_dot_api__pb2


class LoadingService(Protocol):
    async def load_p_d_f(self, request: grpc__generated_dot_api__pb2.PdfLoadRequest, ctx: RequestContext) -> grpc__generated_dot_api__pb2.PdfLoadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class LoadingServiceASGIApplication(ConnectASGIApplication):
    def __init__(self, service: LoadingService, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.LoadingService/LoadPDF": Endpoint.unary(
                    method=MethodInfo(
                        name="LoadPDF",
                        service_name="bibliophage.LoadingService",
                        input=grpc__generated_dot_api__pb2.PdfLoadRequest,
                        output=grpc__generated_dot_api__pb2.PdfLoadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.load_p_d_f,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.LoadingService"


class LoadingServiceClient(ConnectClient):
    async def load_p_d_f(
        self,
        request: grpc__generated_dot_api__pb2.PdfLoadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> grpc__generated_dot_api__pb2.PdfLoadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LoadPDF",
                service_name="bibliophage.LoadingService",
                input=grpc__generated_dot_api__pb2.PdfLoadRequest,
                output=grpc__generated_dot_api__pb2.PdfLoadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )



class DocumentService(Protocol):
    async def store_document(self, request: grpc__generated_dot_api__pb2.DocumentStoreRequest, ctx: RequestContext) -> grpc__generated_dot_api__pb2.DocumentStoreResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DocumentServiceASGIApplication(ConnectASGIApplication):
    def __init__(self, service: DocumentService, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.DocumentService/StoreDocument": Endpoint.unary(
                    method=MethodInfo(
                        name="StoreDocument",
                        service_name="bibliophage.DocumentService",
                        input=grpc__generated_dot_api__pb2.DocumentStoreRequest,
                        output=grpc__generated_dot_api__pb2.DocumentStoreResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.store_document,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.DocumentService"


class DocumentServiceClient(ConnectClient):
    async def store_document(
        self,
        request: grpc__generated_dot_api__pb2.DocumentStoreRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> grpc__generated_dot_api__pb2.DocumentStoreResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StoreDocument",
                service_name="bibliophage.DocumentService",
                input=grpc__generated_dot_api__pb2.DocumentStoreRequest,
                output=grpc__generated_dot_api__pb2.DocumentStoreResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class LoadingServiceSync(Protocol):
    def load_p_d_f(self, request: grpc__generated_dot_api__pb2.PdfLoadRequest, ctx: RequestContext) -> grpc__generated_dot_api__pb2.PdfLoadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class LoadingServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: LoadingServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.LoadingService/LoadPDF": EndpointSync.unary(
                    method=MethodInfo(
                        name="LoadPDF",
                        service_name="bibliophage.LoadingService",
                        input=grpc__generated_dot_api__pb2.PdfLoadRequest,
                        output=grpc__generated_dot_api__pb2.PdfLoadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.load_p_d_f,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.LoadingService"


class LoadingServiceClientSync(ConnectClientSync):
    def load_p_d_f(
        self,
        request: grpc__generated_dot_api__pb2.PdfLoadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> grpc__generated_dot_api__pb2.PdfLoadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LoadPDF",
                service_name="bibliophage.LoadingService",
                input=grpc__generated_dot_api__pb2.PdfLoadRequest,
                output=grpc__generated_dot_api__pb2.PdfLoadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class DocumentServiceSync(Protocol):
    def store_document(self, request: grpc__generated_dot_api__pb2.DocumentStoreRequest, ctx: RequestContext) -> grpc__generated_dot_api__pb2.DocumentStoreResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DocumentServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: DocumentServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.DocumentService/StoreDocument": EndpointSync.unary(
                    method=MethodInfo(
                        name="StoreDocument",
                        service_name="bibliophage.DocumentService",
                        input=grpc__generated_dot_api__pb2.DocumentStoreRequest,
                        output=grpc__generated_dot_api__pb2.DocumentStoreResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.store_document,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.DocumentService"


class DocumentServiceClientSync(ConnectClientSync):
    def store_document(
        self,
        request: grpc__generated_dot_api__pb2.DocumentStoreRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> grpc__generated_dot_api__pb2.DocumentStoreResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StoreDocument",
                service_name="bibliophage.DocumentService",
                input=grpc__generated_dot_api__pb2.DocumentStoreRequest,
                output=grpc__generated_dot_api__pb2.DocumentStoreResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
