[workspace]
authors = ["Leon Welchert <lichturm@posteo.de>"]
channels = ["conda-forge"]
name = "bilbiophage"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
wrapper = { cmd = [
  "./runscript.sh",
]}


[dependencies]
python = ">=3.13.7,<3.14"
langchain-postgres = ">=0.0.15,<0.0.16"
langchain-huggingface = ">=0.3.1,<0.4"
grpcio = ">=1.73.1,<2"
grpcio-tools = ">=1.73.1,<2"
grpcio-reflection = ">=1.45.0,<2"

[pypi-dependencies]
langchain-community = ">=0.3.29, <0.4"
langchain = ">=0.3.27, <0.4"
langchain-core = ">=0.3.76, <0.4"
