# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x0b\x62ibliophage\"\x82\x02\n\x0bLoadRequest\x12\x17\n\x0fpdf_origin_path\x18\x01 \x01(\t\x12\x10\n\x08pdf_name\x18\x02 \x01(\t\x12*\n\npdf_system\x18\x03 \x01(\x0e\x32\x16.bibliophage.RpgSystem\x12.\n\x08pdf_type\x18\x04 \x01(\x0e\x32\x1c.bibliophage.PublicationType\x12\x16\n\x0epdf_page_count\x18\x05 \x01(\x05\x12\x17\n\nchunk_size\x18\x06 \x01(\x05H\x00\x88\x01\x01\x12\x1a\n\rchunk_overlap\x18\x07 \x01(\x05H\x01\x88\x01\x01\x42\r\n\x0b_chunk_sizeB\x10\n\x0e_chunk_overlap\"]\n\x0cLoadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x63hunks_created\x18\x03 \x01(\x05\x12\x13\n\x0b\x64ocument_id\x18\x04 \x01(\t*Y\n\tRpgSystem\x12\x1a\n\x16RPG_SYSTEM_UNSPECIFIED\x10\x00\x12\n\n\x06\x44ND_35\x10\x01\x12\x11\n\rPATHFINDER_1E\x10\x02\x12\x11\n\rPATHFINDER_2E\x10\x03*\x80\x01\n\x0fPublicationType\x12 \n\x1cPUBLICATION_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rCORE_RULEBOOK\x10\x01\x12\x0c\n\x08\x42\x45STIARY\x10\x02\x12\x0e\n\nSUPPLEMENT\x10\x03\x12\r\n\tADVENTURE\x10\x04\x12\x0b\n\x07SETTING\x10\x05\x32P\n\x0eLoadingService\x12>\n\x07LoadPDF\x12\x18.bibliophage.LoadRequest\x1a\x19.bibliophage.LoadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RPGSYSTEM']._serialized_start=382
  _globals['_RPGSYSTEM']._serialized_end=471
  _globals['_PUBLICATIONTYPE']._serialized_start=474
  _globals['_PUBLICATIONTYPE']._serialized_end=602
  _globals['_LOADREQUEST']._serialized_start=27
  _globals['_LOADREQUEST']._serialized_end=285
  _globals['_LOADRESPONSE']._serialized_start=287
  _globals['_LOADRESPONSE']._serialized_end=380
  _globals['_LOADINGSERVICE']._serialized_start=604
  _globals['_LOADINGSERVICE']._serialized_end=684
# @@protoc_insertion_point(module_scope)
