# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_generated import api_pb2 as grpc__generated_dot_api__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_generated/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoadingServiceStub(object):
    """Service definitions - the API endpoints
    RPC method: takes Request, returns Response
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadPDF = channel.unary_unary(
                '/bibliophage.LoadingService/LoadPDF',
                request_serializer=grpc__generated_dot_api__pb2.PdfLoadRequest.SerializeToString,
                response_deserializer=grpc__generated_dot_api__pb2.PdfLoadResponse.FromString,
                _registered_method=True)


class LoadingServiceServicer(object):
    """Service definitions - the API endpoints
    RPC method: takes Request, returns Response
    """

    def LoadPDF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoadingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPDF,
                    request_deserializer=grpc__generated_dot_api__pb2.PdfLoadRequest.FromString,
                    response_serializer=grpc__generated_dot_api__pb2.PdfLoadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bibliophage.LoadingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bibliophage.LoadingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoadingService(object):
    """Service definitions - the API endpoints
    RPC method: takes Request, returns Response
    """

    @staticmethod
    def LoadPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bibliophage.LoadingService/LoadPDF',
            grpc__generated_dot_api__pb2.PdfLoadRequest.SerializeToString,
            grpc__generated_dot_api__pb2.PdfLoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DocumentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreDocument = channel.unary_unary(
                '/bibliophage.DocumentService/StoreDocument',
                request_serializer=grpc__generated_dot_api__pb2.DocumentStoreRequest.SerializeToString,
                response_deserializer=grpc__generated_dot_api__pb2.DocumentStoreResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreDocument,
                    request_deserializer=grpc__generated_dot_api__pb2.DocumentStoreRequest.FromString,
                    response_serializer=grpc__generated_dot_api__pb2.DocumentStoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bibliophage.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bibliophage.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bibliophage.DocumentService/StoreDocument',
            grpc__generated_dot_api__pb2.DocumentStoreRequest.SerializeToString,
            grpc__generated_dot_api__pb2.DocumentStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
