# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_generated/api.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'grpc_generated/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpc_generated/api.proto\x12\x0b\x62ibliophage\"\x85\x02\n\x0ePdfLoadRequest\x12\x17\n\x0fpdf_origin_path\x18\x01 \x01(\t\x12\x10\n\x08pdf_name\x18\x02 \x01(\t\x12*\n\npdf_system\x18\x03 \x01(\x0e\x32\x16.bibliophage.RpgSystem\x12.\n\x08pdf_type\x18\x04 \x01(\x0e\x32\x1c.bibliophage.PublicationType\x12\x16\n\x0epdf_page_count\x18\x05 \x01(\x05\x12\x17\n\nchunk_size\x18\x06 \x01(\x05H\x00\x88\x01\x01\x12\x1a\n\rchunk_overlap\x18\x07 \x01(\x05H\x01\x88\x01\x01\x42\r\n\x0b_chunk_sizeB\x10\n\x0e_chunk_overlap\"p\n\x14\x44ocumentStoreRequest\x12\x15\n\rdocument_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x30\n\rdocument_type\x18\x04 \x01(\x0e\x32\x19.bibliophage.DocumentType\"`\n\x0fPdfLoadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x63hunks_created\x18\x03 \x01(\x05\x12\x13\n\x0b\x64ocument_id\x18\x04 \x01(\t\"9\n\x15\x44ocumentStoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*Y\n\tRpgSystem\x12\x1a\n\x16RPG_SYSTEM_UNSPECIFIED\x10\x00\x12\n\n\x06\x44ND_35\x10\x01\x12\x11\n\rPATHFINDER_1E\x10\x02\x12\x11\n\rPATHFINDER_2E\x10\x03*\x80\x01\n\x0fPublicationType\x12 \n\x1cPUBLICATION_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rCORE_RULEBOOK\x10\x01\x12\x0c\n\x08\x42\x45STIARY\x10\x02\x12\x0e\n\nSUPPLEMENT\x10\x03\x12\r\n\tADVENTURE\x10\x04\x12\x0b\n\x07SETTING\x10\x05*s\n\x0c\x44ocumentType\x12\x1d\n\x19\x44OCUMENT_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04NOTE\x10\x01\x12\x11\n\rLORE_FRAGMENT\x10\x02\x12\r\n\tCHARACTER\x10\x03\x12\x0c\n\x08LOCATION\x10\x04\x12\n\n\x06OBJECT\x10\x05\x32V\n\x0eLoadingService\x12\x44\n\x07LoadPDF\x12\x1b.bibliophage.PdfLoadRequest\x1a\x1c.bibliophage.PdfLoadResponse2i\n\x0f\x44ocumentService\x12V\n\rStoreDocument\x12!.bibliophage.DocumentStoreRequest\x1a\".bibliophage.DocumentStoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_generated.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RPGSYSTEM']._serialized_start=576
  _globals['_RPGSYSTEM']._serialized_end=665
  _globals['_PUBLICATIONTYPE']._serialized_start=668
  _globals['_PUBLICATIONTYPE']._serialized_end=796
  _globals['_DOCUMENTTYPE']._serialized_start=798
  _globals['_DOCUMENTTYPE']._serialized_end=913
  _globals['_PDFLOADREQUEST']._serialized_start=42
  _globals['_PDFLOADREQUEST']._serialized_end=303
  _globals['_DOCUMENTSTOREREQUEST']._serialized_start=305
  _globals['_DOCUMENTSTOREREQUEST']._serialized_end=417
  _globals['_PDFLOADRESPONSE']._serialized_start=419
  _globals['_PDFLOADRESPONSE']._serialized_end=515
  _globals['_DOCUMENTSTORERESPONSE']._serialized_start=517
  _globals['_DOCUMENTSTORERESPONSE']._serialized_end=574
  _globals['_LOADINGSERVICE']._serialized_start=915
  _globals['_LOADINGSERVICE']._serialized_end=1001
  _globals['_DOCUMENTSERVICE']._serialized_start=1003
  _globals['_DOCUMENTSERVICE']._serialized_end=1108
# @@protoc_insertion_point(module_scope)
