// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file api.proto (package bibliophage, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * enums for strict classification of data,
 * rather than freeform JSON/strings
 *
 * @generated from enum bibliophage.DocumentType
 */
export enum DocumentType {
  /**
   * Default/unknown
   *
   * @generated from enum value: DOCUMENT_TYPE_UNSPECIFIED = 0;
   */
  DOCUMENT_TYPE_UNSPECIFIED = 0,

  /**
   * Least specific, unspecified documents will be turned into this
   *
   * @generated from enum value: NOTE = 1;
   */
  NOTE = 1,

  /**
   * Has some authoritative information
   *
   * @generated from enum value: LORE_FRAGMENT = 2;
   */
  LORE_FRAGMENT = 2,

  /**
   * PCs, NPCs, historical figures, ...
   *
   * @generated from enum value: CHARACTER = 3;
   */
  CHARACTER = 3,

  /**
   * Places
   *
   * @generated from enum value: LOCATION = 4;
   */
  LOCATION = 4,

  /**
   * Posessions, Items, Objects, ...
   *
   * @generated from enum value: OBJECT = 5;
   */
  OBJECT = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(DocumentType)
proto3.util.setEnumType(DocumentType, "bibliophage.DocumentType", [
  { no: 0, name: "DOCUMENT_TYPE_UNSPECIFIED" },
  { no: 1, name: "NOTE" },
  { no: 2, name: "LORE_FRAGMENT" },
  { no: 3, name: "CHARACTER" },
  { no: 4, name: "LOCATION" },
  { no: 5, name: "OBJECT" },
]);

/**
 * Request messages - what the client sends
 *
 * @generated from message bibliophage.PdfLoadRequest
 */
export class PdfLoadRequest extends Message<PdfLoadRequest> {
  /**
   * Filesystem path to the PDF
   *
   * @generated from field: string pdf_origin_path = 1;
   */
  pdfOriginPath = "";

  /**
   * Human-readable name (e.g., "Monster Manual")
   *
   * @generated from field: string pdf_name = 2;
   */
  pdfName = "";

  /**
   * Which RPG system
   *
   * @generated from field: string pdf_system = 3;
   */
  pdfSystem = "";

  /**
   * Type of publication
   *
   * @generated from field: string pdf_type = 4;
   */
  pdfType = "";

  /**
   * Number of pages (optional, can be 0)
   *
   * @generated from field: int32 pdf_page_count = 5;
   */
  pdfPageCount = 0;

  /**
   * Chunking parameters
   *
   * Size of text chunks (default: 600)
   *
   * @generated from field: optional int32 chunk_size = 6;
   */
  chunkSize?: number;

  /**
   * Overlap between chunks (default: 50)
   *
   * @generated from field: optional int32 chunk_overlap = 7;
   */
  chunkOverlap?: number;

  /**
   * PDF file data
   *
   * @generated from field: bytes file_data = 8;
   */
  fileData = new Uint8Array(0);

  constructor(data?: PartialMessage<PdfLoadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.PdfLoadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pdf_origin_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pdf_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "pdf_system", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "pdf_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "pdf_page_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "chunk_size", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 7, name: "chunk_overlap", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 8, name: "file_data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PdfLoadRequest {
    return new PdfLoadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PdfLoadRequest {
    return new PdfLoadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PdfLoadRequest {
    return new PdfLoadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PdfLoadRequest | PlainMessage<PdfLoadRequest> | undefined, b: PdfLoadRequest | PlainMessage<PdfLoadRequest> | undefined): boolean {
    return proto3.util.equals(PdfLoadRequest, a, b);
  }
}

/**
 * @generated from message bibliophage.DocumentStoreRequest
 */
export class DocumentStoreRequest extends Message<DocumentStoreRequest> {
  /**
   * Human-readable name (e.g., "Monster Manual")
   *
   * @generated from field: string document_name = 1;
   */
  documentName = "";

  /**
   * raw text content of the document
   *
   * @generated from field: string content = 2;
   */
  content = "";

  /**
   * Type of document
   *
   * @generated from field: bibliophage.DocumentType document_type = 4;
   */
  documentType = DocumentType.DOCUMENT_TYPE_UNSPECIFIED;

  constructor(data?: PartialMessage<DocumentStoreRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.DocumentStoreRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "document_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "document_type", kind: "enum", T: proto3.getEnumType(DocumentType) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DocumentStoreRequest {
    return new DocumentStoreRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DocumentStoreRequest {
    return new DocumentStoreRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DocumentStoreRequest {
    return new DocumentStoreRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DocumentStoreRequest | PlainMessage<DocumentStoreRequest> | undefined, b: DocumentStoreRequest | PlainMessage<DocumentStoreRequest> | undefined): boolean {
    return proto3.util.equals(DocumentStoreRequest, a, b);
  }
}

/**
 * Response messages - what the server sends back
 *
 * @generated from message bibliophage.PdfLoadResponse
 */
export class PdfLoadResponse extends Message<PdfLoadResponse> {
  /**
   * Did it work?
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  /**
   * How many chunks were stored
   *
   * @generated from field: int32 chunks_created = 3;
   */
  chunksCreated = 0;

  /**
   * Unique ID for this ingested document
   *
   * @generated from field: string document_id = 4;
   */
  documentId = "";

  constructor(data?: PartialMessage<PdfLoadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.PdfLoadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "chunks_created", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PdfLoadResponse {
    return new PdfLoadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PdfLoadResponse {
    return new PdfLoadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PdfLoadResponse {
    return new PdfLoadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PdfLoadResponse | PlainMessage<PdfLoadResponse> | undefined, b: PdfLoadResponse | PlainMessage<PdfLoadResponse> | undefined): boolean {
    return proto3.util.equals(PdfLoadResponse, a, b);
  }
}

/**
 * @generated from message bibliophage.DocumentStoreResponse
 */
export class DocumentStoreResponse extends Message<DocumentStoreResponse> {
  /**
   * Did it work?
   *
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * Human-readable status/error message
   *
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<DocumentStoreResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bibliophage.DocumentStoreResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DocumentStoreResponse {
    return new DocumentStoreResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DocumentStoreResponse {
    return new DocumentStoreResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DocumentStoreResponse {
    return new DocumentStoreResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DocumentStoreResponse | PlainMessage<DocumentStoreResponse> | undefined, b: DocumentStoreResponse | PlainMessage<DocumentStoreResponse> | undefined): boolean {
    return proto3.util.equals(DocumentStoreResponse, a, b);
  }
}

