# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bibliophage/v1alpha1/document.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'bibliophage/v1alpha1/document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#bibliophage/v1alpha1/document.proto\x12\x0b\x62ibliophage\"p\n\x14\x44ocumentStoreRequest\x12\x15\n\rdocument_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x30\n\rdocument_type\x18\x04 \x01(\x0e\x32\x19.bibliophage.DocumentType\"9\n\x15\x44ocumentStoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*s\n\x0c\x44ocumentType\x12\x1d\n\x19\x44OCUMENT_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04NOTE\x10\x01\x12\x11\n\rLORE_FRAGMENT\x10\x02\x12\r\n\tCHARACTER\x10\x03\x12\x0c\n\x08LOCATION\x10\x04\x12\n\n\x06OBJECT\x10\x05\x32i\n\x0f\x44ocumentService\x12V\n\rStoreDocument\x12!.bibliophage.DocumentStoreRequest\x1a\".bibliophage.DocumentStoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bibliophage.v1alpha1.document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENTTYPE']._serialized_start=225
  _globals['_DOCUMENTTYPE']._serialized_end=340
  _globals['_DOCUMENTSTOREREQUEST']._serialized_start=52
  _globals['_DOCUMENTSTOREREQUEST']._serialized_end=164
  _globals['_DOCUMENTSTORERESPONSE']._serialized_start=166
  _globals['_DOCUMENTSTORERESPONSE']._serialized_end=223
  _globals['_DOCUMENTSERVICE']._serialized_start=342
  _globals['_DOCUMENTSERVICE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
