# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: bibliophage/v1alpha1/document.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import bibliophage.v1alpha1.document_pb2 as bibliophage_dot_v1alpha1_dot_document__pb2


class DocumentService(Protocol):
    async def store_document(self, request: bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DocumentServiceASGIApplication(ConnectASGIApplication):
    def __init__(self, service: DocumentService, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.DocumentService/StoreDocument": Endpoint.unary(
                    method=MethodInfo(
                        name="StoreDocument",
                        service_name="bibliophage.DocumentService",
                        input=bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreRequest,
                        output=bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.store_document,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.DocumentService"


class DocumentServiceClient(ConnectClient):
    async def store_document(
        self,
        request: bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StoreDocument",
                service_name="bibliophage.DocumentService",
                input=bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreRequest,
                output=bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class DocumentServiceSync(Protocol):
    def store_document(self, request: bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DocumentServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: DocumentServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.DocumentService/StoreDocument": EndpointSync.unary(
                    method=MethodInfo(
                        name="StoreDocument",
                        service_name="bibliophage.DocumentService",
                        input=bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreRequest,
                        output=bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.store_document,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.DocumentService"


class DocumentServiceClientSync(ConnectClientSync):
    def store_document(
        self,
        request: bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StoreDocument",
                service_name="bibliophage.DocumentService",
                input=bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreRequest,
                output=bibliophage_dot_v1alpha1_dot_document__pb2.DocumentStoreResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
