# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bibliophage/v1alpha1/pdf.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'bibliophage/v1alpha1/pdf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62ibliophage/v1alpha1/pdf.proto\x12\x0b\x62ibliophage\"\xe2\x01\n\x0ePdfLoadRequest\x12\x17\n\x0fpdf_origin_path\x18\x01 \x01(\t\x12\x10\n\x08pdf_name\x18\x02 \x01(\t\x12\x12\n\npdf_system\x18\x03 \x01(\t\x12\x10\n\x08pdf_type\x18\x04 \x01(\t\x12\x16\n\x0epdf_page_count\x18\x05 \x01(\x05\x12\x17\n\nchunk_size\x18\x06 \x01(\x05H\x00\x88\x01\x01\x12\x1a\n\rchunk_overlap\x18\x07 \x01(\x05H\x01\x88\x01\x01\x12\x11\n\tfile_data\x18\x08 \x01(\x0c\x42\r\n\x0b_chunk_sizeB\x10\n\x0e_chunk_overlap\"`\n\x0fPdfLoadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x63hunks_created\x18\x03 \x01(\x05\x12\x13\n\x0b\x64ocument_id\x18\x04 \x01(\t2V\n\x0eLoadingService\x12\x44\n\x07LoadPDF\x12\x1b.bibliophage.PdfLoadRequest\x1a\x1c.bibliophage.PdfLoadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bibliophage.v1alpha1.pdf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PDFLOADREQUEST']._serialized_start=48
  _globals['_PDFLOADREQUEST']._serialized_end=274
  _globals['_PDFLOADRESPONSE']._serialized_start=276
  _globals['_PDFLOADRESPONSE']._serialized_end=372
  _globals['_LOADINGSERVICE']._serialized_start=374
  _globals['_LOADINGSERVICE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
