# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: bibliophage/v1alpha1/pdf.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import bibliophage.v1alpha1.pdf_pb2 as bibliophage_dot_v1alpha1_dot_pdf__pb2


class LoadingService(Protocol):
    async def load_p_d_f(self, request: bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class LoadingServiceASGIApplication(ConnectASGIApplication):
    def __init__(self, service: LoadingService, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.LoadingService/LoadPDF": Endpoint.unary(
                    method=MethodInfo(
                        name="LoadPDF",
                        service_name="bibliophage.LoadingService",
                        input=bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadRequest,
                        output=bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.load_p_d_f,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.LoadingService"


class LoadingServiceClient(ConnectClient):
    async def load_p_d_f(
        self,
        request: bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LoadPDF",
                service_name="bibliophage.LoadingService",
                input=bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadRequest,
                output=bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class LoadingServiceSync(Protocol):
    def load_p_d_f(self, request: bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadRequest, ctx: RequestContext) -> bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class LoadingServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: LoadingServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/bibliophage.LoadingService/LoadPDF": EndpointSync.unary(
                    method=MethodInfo(
                        name="LoadPDF",
                        service_name="bibliophage.LoadingService",
                        input=bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadRequest,
                        output=bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.load_p_d_f,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bibliophage.LoadingService"


class LoadingServiceClientSync(ConnectClientSync):
    def load_p_d_f(
        self,
        request: bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LoadPDF",
                service_name="bibliophage.LoadingService",
                input=bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadRequest,
                output=bibliophage_dot_v1alpha1_dot_pdf__pb2.PdfLoadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
